// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDxWy57ENgndyCmcG46ZMB6VXZ87fPwI',
    appId: '1:74808353748:web:f03e01be13cf5bc9eeac41',
    messagingSenderId: '74808353748',
    projectId: 'boutigi-app',
    authDomain: 'boutigi-app.firebaseapp.com',
    storageBucket: 'boutigi-app.firebasestorage.app',
    measurementId: 'G-E9GGW6804T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcMEEB1_mM1crJpIs-UUyIHrQ313oFpY',
    appId: '1:74808353748:android:62eb49830fb10519eeac41',
    messagingSenderId: '74808353748',
    projectId: 'boutigi-app',
    storageBucket: 'boutigi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHu8nY2axZ7nFfeQJrejp5F7QcmWaa49c',
    appId: '1:74808353748:ios:4e1f01232b46ee66eeac41',
    messagingSenderId: '74808353748',
    projectId: 'boutigi-app',
    storageBucket: 'boutigi-app.firebasestorage.app',
    iosBundleId: 'com.example.boutigiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHu8nY2axZ7nFfeQJrejp5F7QcmWaa49c',
    appId: '1:74808353748:ios:4e1f01232b46ee66eeac41',
    messagingSenderId: '74808353748',
    projectId: 'boutigi-app',
    storageBucket: 'boutigi-app.firebasestorage.app',
    iosBundleId: 'com.example.boutigiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwDxWy57ENgndyCmcG46ZMB6VXZ87fPwI',
    appId: '1:74808353748:web:85a57f9e19ebcc38eeac41',
    messagingSenderId: '74808353748',
    projectId: 'boutigi-app',
    authDomain: 'boutigi-app.firebaseapp.com',
    storageBucket: 'boutigi-app.firebasestorage.app',
    measurementId: 'G-EBKFSJGFRB',
  );
}
